export const OPEN_CREATE_CHARACTER_DIALOG = 'characters/open-create-character-dialog'
export const CLOSE_CREATE_CHARACTER_DIALOG = 'characters/close-create-character-dialog'
export const CREATE_CHARACTER = 'characters/create-character'
export const SELECT_CHARACTER = 'characters/select-character'
export const DESELECT_CHARACTER = 'characters/deselect-character'
export const ENABLE_CHARACTER_EDIT_MODE = 'characters/enable-character-edit-mode'
export const DISABLE_CHARACTER_EDIT_MODE = 'characters/disable-character-edit-mode'
