export const OPEN_STORY_STARTED = 'story/open-story'
export const OPEN_STORY_SUCCESSFUL = 'story/open-story-sucessful'
export const OPEN_STORY_FAILED = 'story/open-story-failed'
export const OPEN_STORY_CANCELED = 'story/open-story-canceled'
export const CLOSE_OPEN_STORY_DIALOG = 'story/close-open-story-dialog'
