export { default as reducer } from './reducer'
export { openPreferences, closePreferences } from './database'
export { isDarkThemeEnabled, enableDarkTheme, disableDarkTheme } from './dark-theme'
export { getRecentlyOpenedFiles, addOrUpdateRecentlyOpenedFile, removeRecentlyOpenedFile, pinRecentlyOpenedFile, unpinRecentlyOpenedFile } from './recently-opened-files'
export { default as registerRequestHandlers } from './request-handlers'
