export { default as initPreferences } from './init'
export { isDarkThemeEnabled, setDarkThemeEnabled } from './dark-theme'
export { getRecentlyOpenedFiles, addOrUpdateRecentlyOpenedFile, removeRecentlyOpenedFile } from './recently-opened-files'
export { default as closePreferences } from './close'
export { default as registerRequestHandlers } from './request-handlers'
