export const ADD_CHARACTER = "ADD_CHARACTER";
export const CHANGE_CHARACTER_NAME = "CHANGE_CHARACTER_NAME";
export const SET_FILTER = "SET_FILTER";
export const SELECT_CHARACTER = "SELECT_CHARACTER";
export const UNSELECT_CHARACTER = "UNSELECT_CHARACTER";
