export const ADD_WINDOW = 'windows/add-window'
export const REMOVE_WINDOW = 'windows/remove-window'
export const SET_WINDOW_IS_READY = 'windows/set-window-is-ready'
export const SET_WINDOW_STORY_PATH = 'windows/set-window-story-path'
export const SET_WINDOW_FOCUS_STATUS = 'windows/set-window-focus-status'
export const WINDOW_FOCUS_CHANGED = 'windows/window-focus-changed'
