export const GET_RECENTLY_OPENED_FILES = 'preferences/recently-opened-files/get'
export const PIN_RECENTLY_OPENED_FILE = 'preferences/recently-opened-files/pin'
export const UNPIN_RECENTLY_OPENED_FILE = 'preferences/recently-opened-files/unpin'
export const REMOVE_RECENTLY_OPENED_FILE = 'preferences/recently-opened-files/remove'
export const ADD_RECENTLY_OPENED_FILE = 'preferences/recently-opened-files/add'
