
export const CHANGE_CHARACTER_NAME = "CHANGE_CHARACTER_NAME";

// UI ACTIONS
export const DESELECT_CHARACTER = "DESELECT_CHARACTER";
export const SELECT_CHARACTER = "SELECT_CHARACTER";
export const SET_FILTER = "SET_FILTER";
export const CHANGE_SECTION = "CHANGE_SECTION";
export const SHOW_MSG = "SHOW_MSG";
export const SHOW_ERROR_MSG = "SHOW_ERROR_MSG";
export const SHOW_SUCCESS_MSG = "SHOW_SUCCESS_MSG";
export const CLOSE_MSG = "CLOSE_MSG";
export const SET_SAVING_TYPE = "SET_SAVING_TYPE";

// MODEL ACTIONS
//---- CHARACTER
export const ADD_CHARACTER = "ADD_CHARACTER";
export const CREATE_CHARACTER = "CREATE_CHARACTER";
export const REQUEST_CHARACTERS = "REQUEST_CHARACTERS";
export const RECEIVE_CHARACTERS = "RECEIVE_CHARACTERS";
export const SAVE_CHARACTER = "SAVE_CHARACTER";
export const DELETE_CHARACTER = "DELETE_CHARACTER";
export const UNDO = "UNDO";
export const REDO = "REDO";
export const REQUEST_CHARACTER = "REQUEST_CHARACTER";
export const REQUEST_UNDO = "REQUEST_UNDO";
export const RECEIVE_UNDO = "RECEIVE_UNDO";
export const REQUEST_CAN_UNDO = "REQUEST_CAN_UNDO";
export const RECEIVE_CAN_UNDO = "RECEIVE_CAN_UNDO";

//---- STORY
export const REQUEST_STORY = "REQUEST_STORY";
export const RECEIVE_STORY = "RECEIVE_STORY";

//---- ACTION MENU
export const OPEN_SETTINGS = "OPEN_SETTINGS";
export const OPEN_ABOUT = "OPEN_ABOUT";