
export const CHANGE_CHARACTER_NAME = "CHANGE_CHARACTER_NAME";

// UI ACTIONS
export const DESELECT_CHARACTER = "DESELECT_CHARACTER";
export const SELECT_CHARACTER = "SELECT_CHARACTER";
export const SET_FILTER = "SET_FILTER";
export const CHANGE_SECTION = "CHANGE_SECTION";

// MODEL ACTIONS
//---- CHARACTER
export const ADD_CHARACTER = "ADD_CHARACTER";
export const CREATE_CHARACTER = "CREATE_CHARACTER";
export const REQUEST_CHARACTERS = "REQUEST_CHARACTERS";
export const RECEIVE_CHARACTERS = "RECEIVE_CHARACTERS";
export const SAVE_CHARACTER = "SAVE_CHARACTER";
export const DELETE_CHARACTER = "DELETE_CHARACTER";
export const UNDO = "UNDO";
export const REDO = "REDO";

//---- STORY
export const REQUEST_STORY = "REQUEST_STORY";
export const RECEIVE_STORY = "RECEIVE_STORY";

//---- ACTION MENU
export const OPEN_SETTINGS = "OPEN_SETTINGS";
export const OPEN_ABOUT = "OPEN_ABOUT";