export const GET_CHARACTERS = 'characters/get-characters'
export const CREATE_CHARACTER = 'characters/create-character'
export const FIND_CHARACTERS = 'characters/find-characters'
export const GET_PROFILE = 'characters/get-profile'
export const UPDATE_CHARACTER = 'characters/update-character'
export const UPDATE_ENTRY = 'characters/update-entry'
